### ISSUE TITLE
Deployment successful but cant see results.

### ISSUE THREAD

**Issue by edy-chan** [alertlogic/ci_lambda_checks#31]
I am struggling to get this working, the CF is deploy successfully and I have done per documentation. 

The lambda cloudwatch error:
`2018-08-21T07:02:26.075Z	01af3731-a510-11e8-8abb-6b5eed724042	TypeError: Cannot read property '1' of null
at getAccountIdFromSubject (/var/task/driver.js:498:46)
at exports.handler (/var/task/driver.js:42:36)
END RequestId: 01af3731-a510-11e8-8abb-6b5eed724042
REPORT RequestId: 01af3731-a510-11e8-8abb-6b5eed724042	Duration: 267.85 ms	Billed Duration: 300 ms Memory Size: 128 MB	Max Memory Used: 46 MB	
RequestId: 01af3731-a510-11e8-8abb-6b5eed724042 Process exited before completing request`

I have triggered Inspector Scan and waited for it to complete. I could see the lambda functions getting triggered. And there's no other obvious error observed (other than the above)
I did not receive any result from Inspector, Config or the Custom Checks in the AlertLogic console. Where will the results be displayed?

**Comment by BarrySkidmore** [comment]
https://github.com/alertlogic/ci_lambda_checks/pull/29

The TopicARN needs to have the account id properly set up for the software to successfully identify the account id for processing.

You can see the code here:
https://github.com/alertlogic/ci_lambda_checks/pull/29/commits/51717b2e2284938cf26b030b9342cb15622e560b

**Comment by edy-chan** [comment]
I do not think the issue is on the resource arn. I have seen two sns event from aws config, similar event message. One error-ed and one did not. And I could see the function successfully extract the account number in the log. I have passed some sample logs to Alertlogic Support team but no reply yet.  Also for the successful one which ended with  ".... Successfully dispatched AWS Config Event." I do not see the result in AlertLogic console. Where will this result be displayed?

Apologies if I am not providing enough useful details here. Is there any specific log that I can provide to help with this?
